version: "3.8"

services:
  python:
    build: ./python
    volumes:
      - shared-data:/results
  java:
    build: ./java
    volumes:
      - shared-data:/results
  javascript:
    build: ./javascript
    volumes:
      - shared-data:/results
  c:
    build: ./c
    volumes:
      - shared-data:/results
  php:
    build: ./php
    volumes:
      - shared-data:/results

volumes:
  shared-data:
